# fly.toml app configuration file generated for minecraft-afk-bot123 on 2025-06-28T15:03:44Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'minecraft-afk-bot123'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
